<?php

declare(strict_types=1);

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Osiset\ShopifyApp\Exceptions\MissingShopDomainException;
use Osiset\ShopifyApp\Exceptions\SignatureVerificationException;
use Sentry\Laravel\Integration;
use Throwable;

use function redirect;

class Handler extends ExceptionHandler
{
    /**
     * A list of exception types with their corresponding custom log levels.
     *
     * @var array<class-string<\Throwable>, \Psr\Log\LogLevel::*>
     */
    protected $levels = [
    ];

    /**
     * A list of the exception types that are not reported.
     *
     * @var array<int, class-string<\Throwable>>
     */
    protected $dontReport = [
    ];

    /**
     * A list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(static function (Throwable $e) {
            Integration::captureUnhandledException($e);
        });
    }

    public function render($request, Throwable $e)
    {
        /*
         * Redirect to Login Page if Missing Shop Domain Exception throws
         */
        if ($e instanceof MissingShopDomainException) {
            return redirect()->route('login');
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }

    public function report(Throwable $exception)
    {
        if ($exception instanceof MissingShopDomainException) {
            return;
        }
        if ($exception instanceof SignatureVerificationException) {
            \Log::error('SignatureVerificationException error occurs.');
            return;
        }

        parent::report($exception);
    }
}
