# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "94c44ac2dcc26cda3b03cbbebbe88192"
name = "iconify-app"
application_url = "https://blockheadedly-camailed-yon.ngrok-free.dev"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_draft_orders,read_draft_orders,read_fulfillments,write_fulfillments,write_inventory,read_inventory,read_orders,write_orders,read_products,read_themes,write_themes"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://blockheadedly-camailed-yon.ngrok-free.dev/authenticate"
]
